"use client";
import { useMemo, useRef, useState } from "react";
import Link from "next/link";
import { categories, ratings } from "@/lib/modifier-schema";

type Modifier = { id: string; internalKey: string; aura: string; displayText: string; statDescription: string | null; minRoll: number | null; maxRoll: number | null; weight: number | null; category: string; notes: string | null; enabled: boolean; ratings: { rating: string }[] };
const blank = { internalKey: "", aura: "", displayText: "", statDescription: "", minRoll: "", maxRoll: "", weight: "", category: "Other", notes: "", enabled: true, rating: "" };

export function ModifierCatalog({ initialModifiers }: { initialModifiers: Modifier[] }) {
  const [items, setItems] = useState(initialModifiers); const [query, setQuery] = useState(""); const [aura, setAura] = useState("");
  const [editing, setEditing] = useState<string | null>(null); const [form, setForm] = useState<Record<string, string | boolean>>(blank); const [notice, setNotice] = useState(""); const file = useRef<HTMLInputElement>(null);
  const auras = [...new Set(items.map((item) => item.aura))].sort();
  const shown = useMemo(() => items.filter((item) => (!aura || item.aura === aura) && `${item.aura} ${item.displayText} ${item.internalKey}`.toLowerCase().includes(query.toLowerCase())), [items, query, aura]);
  const edit = (item?: Modifier) => { setEditing(item?.id ?? "new"); setForm(item ? { ...item, statDescription: item.statDescription ?? "", minRoll: item.minRoll?.toString() ?? "", maxRoll: item.maxRoll?.toString() ?? "", weight: item.weight?.toString() ?? "", notes: item.notes ?? "", rating: item.ratings[0]?.rating ?? "" } : blank); setNotice(""); };
  const refresh = async () => setItems(await (await fetch("/api/modifiers")).json());
  const save = async (event: React.FormEvent) => { event.preventDefault(); const payload = { ...form, minRoll: form.minRoll === "" ? null : Number(form.minRoll), maxRoll: form.maxRoll === "" ? null : Number(form.maxRoll), weight: form.weight === "" ? null : Number(form.weight) }; const response = await fetch(editing === "new" ? "/api/modifiers" : `/api/modifiers/${editing}`, { method: editing === "new" ? "POST" : "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); if (!response.ok) return setNotice(body.error); await refresh(); setEditing(null); setNotice("Modifier saved."); };
  const importFile = async (selected?: File) => { if (!selected) return; const csv = selected.name.endsWith(".csv"); const response = await fetch("/api/modifiers/import", { method: "POST", headers: { "Content-Type": csv ? "text/csv" : "application/json" }, body: await selected.text() }); const body = await response.json(); setNotice(response.ok ? `${body.imported} modifier row(s) imported.` : body.error); if (response.ok) await refresh(); };
  return <>
    <header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 text-xs font-semibold uppercase tracking-[.22em] text-cyan">Data foundation</div><h1 className="text-3xl font-semibold text-white">Modifier Catalog</h1><p className="mt-2 max-w-2xl text-sm text-slate-400">Maintain stable modifier identities and research annotations. Catalog values are user-supplied—not verified game mechanics.</p></div><button onClick={() => edit()} className="rounded-lg bg-cyan px-4 py-2 text-sm font-semibold text-slate-950 hover:bg-cyan/90">+ Add modifier</button></header>
    <section className="mb-5 grid gap-3 rounded-xl border border-slate-800 bg-panel/80 p-4 md:grid-cols-[1fr_180px_auto]">
      <input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search aura, text, or internal key…"/><select value={aura} onChange={(e) => setAura(e.target.value)}><option value="">All auras</option>{auras.map((value) => <option key={value}>{value}</option>)}</select><div className="flex gap-2"><button onClick={() => file.current?.click()} className="rounded-lg border border-slate-700 px-3 text-sm hover:border-slate-500">Import</button><input ref={file} type="file" accept=".csv,.json" hidden onChange={(e) => importFile(e.target.files?.[0])}/><Link href="/api/modifiers/export" className="rounded-lg border border-slate-700 px-3 py-2 text-sm hover:border-slate-500">CSV</Link><Link href="/api/modifiers/export?format=json" className="rounded-lg border border-slate-700 px-3 py-2 text-sm hover:border-slate-500">JSON</Link></div>
    </section>
    {notice && <div className="mb-4 rounded-lg border border-cyan/20 bg-cyan/5 px-4 py-3 text-sm text-cyan">{notice}</div>}
    <div className="overflow-hidden rounded-xl border border-slate-800 bg-panel/70"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-slate-800 bg-slate-950/40 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-4">Modifier</th><th className="px-4">Aura</th><th className="px-4">Category</th><th className="px-4">Roll range</th><th className="px-4">Rating</th><th className="px-4">State</th><th/></tr></thead><tbody className="divide-y divide-slate-800">{shown.map((item) => <tr key={item.id} className="hover:bg-slate-800/30"><td className="px-5 py-4"><div className="font-medium text-slate-100">{item.displayText}</div><code className="text-xs text-slate-500">{item.internalKey}</code></td><td className="px-4 text-cyan">{item.aura}</td><td className="px-4"><span className="rounded-md bg-slate-800 px-2 py-1 text-xs">{item.category}</span></td><td className="px-4 text-slate-400">{item.minRoll == null && item.maxRoll == null ? "—" : `${item.minRoll ?? "?"} – ${item.maxRoll ?? "?"}`}</td><td className="px-4 font-semibold text-gold">{item.ratings[0]?.rating ?? "—"}</td><td className="px-4"><span className={item.enabled ? "text-emerald-400" : "text-slate-600"}>{item.enabled ? "Enabled" : "Disabled"}</span></td><td className="px-5 text-right"><button onClick={() => edit(item)} className="text-slate-400 hover:text-white">Edit</button></td></tr>)}</tbody></table></div>{shown.length === 0 && <div className="py-16 text-center text-sm text-slate-500">No modifiers match this view. Import the template or add one manually.</div>}<div className="border-t border-slate-800 px-5 py-3 text-xs text-slate-500">Showing {shown.length} of {items.length} modifiers</div></div>
    {editing && <div className="fixed inset-0 z-20 grid place-items-center overflow-y-auto bg-black/75 p-4"><form onSubmit={save} className="my-6 w-full max-w-2xl rounded-2xl border border-slate-700 bg-panel p-6 shadow-2xl"><div className="mb-6 flex justify-between"><div><h2 className="text-xl font-semibold text-white">{editing === "new" ? "Add modifier" : "Edit modifier"}</h2><p className="mt-1 text-xs text-slate-500">Use a stable, lowercase internal key.</p></div><button type="button" onClick={() => setEditing(null)} className="text-slate-500 hover:text-white">✕</button></div><div className="grid gap-4 md:grid-cols-2">{[["internalKey","Internal key"],["aura","Aura"],["displayText","Display text"],["statDescription","Stat description"]].map(([key,label]) => <label key={key} className={key === "displayText" || key === "statDescription" ? "md:col-span-2" : ""}><span className="mb-1 block text-xs text-slate-400">{label}</span><input required={!["statDescription"].includes(key)} className="w-full" value={String(form[key])} onChange={(e) => setForm({...form,[key]:e.target.value})}/></label>)}<label><span className="mb-1 block text-xs text-slate-400">Minimum roll</span><input type="number" step="any" className="w-full" value={String(form.minRoll)} onChange={(e) => setForm({...form,minRoll:e.target.value})}/></label><label><span className="mb-1 block text-xs text-slate-400">Maximum roll</span><input type="number" step="any" className="w-full" value={String(form.maxRoll)} onChange={(e) => setForm({...form,maxRoll:e.target.value})}/></label><label><span className="mb-1 block text-xs text-slate-400">Category</span><select className="w-full" value={String(form.category)} onChange={(e) => setForm({...form,category:e.target.value})}>{categories.map((value) => <option key={value}>{value}</option>)}</select></label><label><span className="mb-1 block text-xs text-slate-400">Research rating</span><select className="w-full" value={String(form.rating)} onChange={(e) => setForm({...form,rating:e.target.value})}>{ratings.map((value) => <option key={value} value={value}>{value || "Unrated"}</option>)}</select></label><label className="md:col-span-2"><span className="mb-1 block text-xs text-slate-400">Notes</span><textarea className="w-full" value={String(form.notes)} onChange={(e) => setForm({...form,notes:e.target.value})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form.enabled)} onChange={(e) => setForm({...form,enabled:e.target.checked})}/> Enabled for future combination generation</label></div>{notice && <p className="mt-4 text-sm text-rose-400">{notice}</p>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setEditing(null)} className="rounded-lg border border-slate-700 px-4 py-2 text-sm">Cancel</button><button className="rounded-lg bg-cyan px-4 py-2 text-sm font-semibold text-slate-950">Save modifier</button></div></form></div>}
  </>;
}
